-- Tier 1: Populate file_assets + cms_media_assets + hero_banners + hero_banner_pages + JSONB refs
-- Generated by session 2026-07-30

-- === STATEMENT 1: 31 file_assets rows ===
INSERT INTO file_assets (id, owner_type, owner_id, original_filename, storage_disk, storage_path, mime_type, file_size_bytes, file_hash_sha256, is_public, is_archived, metadata, uploaded_at, created_at, updated_at, uploaded_by) VALUES
  ('file_asset_01KYSW47BAWB9SCMZ4GV2P8NVB', 'static_page_attachment', 'cms_media_01KYSW47BA46ZQ4QG8W59SP52H', 'edited-photo-10.jpg', 'public', 'cms-media/edited-photo-10.jpg', 'image/jpeg', 938858, 'dfc7ae4c24971eeff565bfc176bb7446e9b5bb337d09768717fafded76b2d045', true, false, '{}'::jsonb, NOW(), NOW(), NOW(), 'system'),
  ('file_asset_01KYSW47BAPQ0ZYXH33D2WD0Z5', 'static_page_attachment', 'cms_media_01KYSW47BA4ZW1GHHCDTAVNC9G', 'edited-photo-11.jpg', 'public', 'cms-media/edited-photo-11.jpg', 'image/jpeg', 918142, 'f7280826c1ce58a80c514001ff95f560814b063b4f0c75b7ddee8334053fe4de', true, false, '{}'::jsonb, NOW(), NOW(), NOW(), 'system'),
  ('file_asset_01KYSW47BAC5845PPTB9P8R172', 'static_page_attachment', 'cms_media_01KYSW47BA4HSY4DZYWERHQ0TX', 'edited-photo-12.jpg', 'public', 'cms-media/edited-photo-12.jpg', 'image/jpeg', 727687, '936ee10242a9b6660c69f7624731ff5773e1aee7fdaad36da75598d0bfcaba9e', true, false, '{}'::jsonb, NOW(), NOW(), NOW(), 'system'),
  ('file_asset_01KYSW47BAEDAFVNGTDPV9CGCP', 'static_page_attachment', 'cms_media_01KYSW47BA7Q3R3AN4E192S1H2', 'edited-photo-13.jpg', 'public', 'cms-media/edited-photo-13.jpg', 'image/jpeg', 872944, 'b5528eda53cad8bbbdf4512a98fd412b99527efac288eb2ac0bf3aaabd450e21', true, false, '{}'::jsonb, NOW(), NOW(), NOW(), 'system'),
  ('file_asset_01KYSW47BA62T3CJB1R2YCXW7G', 'static_page_attachment', 'cms_media_01KYSW47BAX7JXZ3333RJZGSVX', 'edited-photo-14.jpg', 'public', 'cms-media/edited-photo-14.jpg', 'image/jpeg', 933319, '7c2447a47eead8df7863bdaf9a8738950bab4a4a2f459e4b1796f9af6ba00718', true, false, '{}'::jsonb, NOW(), NOW(), NOW(), 'system'),
  ('file_asset_01KYSW47BAT0PNX5PHGVB1AKFZ', 'static_page_attachment', 'cms_media_01KYSW47BAWYA7BPSQA91KR5YX', 'edited-photo-15.jpg', 'public', 'cms-media/edited-photo-15.jpg', 'image/jpeg', 970176, 'c876a191cac050e2392bccedd714cb3d89f744edbde5bc8ecbb4936fe6eb53dc', true, false, '{}'::jsonb, NOW(), NOW(), NOW(), 'system'),
  ('file_asset_01KYSW47BA3XPPKBPQ829AKMJE', 'static_page_attachment', 'cms_media_01KYSW47BA1ECS6G74HMCB5CNC', 'edited-photo-16.jpg', 'public', 'cms-media/edited-photo-16.jpg', 'image/jpeg', 2190056, '3bd2a3f4ac5844204db1e05096d0370ea9d70073d28df491d09d83c77a51bdb6', true, false, '{}'::jsonb, NOW(), NOW(), NOW(), 'system'),
  ('file_asset_01KYSW47BAXA0W9G3J35F7MK59', 'static_page_attachment', 'cms_media_01KYSW47BA43CZ9M0GRF4JQ8Z7', 'edited-photo-17.jpg', 'public', 'cms-media/edited-photo-17.jpg', 'image/jpeg', 823672, '76c38b7207a1f8fdee1014e50551a4172dc35850434a217bbcf1d9904af1844a', true, false, '{}'::jsonb, NOW(), NOW(), NOW(), 'system'),
  ('file_asset_01KYSW47BA25PXSV18JEWPZXSN', 'static_page_attachment', 'cms_media_01KYSW47BATDEX0FBAAPKVWW63', 'edited-photo-18.jpg', 'public', 'cms-media/edited-photo-18.jpg', 'image/jpeg', 1907893, 'fea08118d31958ec351995ead5f063654d50f98ff3e0a04586071acd5387e060', true, false, '{}'::jsonb, NOW(), NOW(), NOW(), 'system'),
  ('file_asset_01KYSW47BAYJXA4RS6YSBBM85D', 'static_page_attachment', 'cms_media_01KYSW47BAAWA7XKR4CJS1A3V1', 'edited-photo-19.jpg', 'public', 'cms-media/edited-photo-19.jpg', 'image/jpeg', 2178988, 'd73300f81ce90260a970262e9a64bbc424af8302ced50805d5c662524c1799be', true, false, '{}'::jsonb, NOW(), NOW(), NOW(), 'system'),
  ('file_asset_01KYSW47BA28TDPPSYE6P1JSNE', 'static_page_attachment', 'cms_media_01KYSW47BA80FFZGBZD0CMP4ST', 'edited-photo-02.jpg', 'public', 'cms-media/edited-photo-02.jpg', 'image/jpeg', 1823696, '4de844eeb697f02a8105ae302b75692e744f51208f74f0dbcbdbe1cfd8a6fe7f', true, false, '{}'::jsonb, NOW(), NOW(), NOW(), 'system'),
  ('file_asset_01KYSW47BABC5SMGFHB43Q19D1', 'static_page_attachment', 'cms_media_01KYSW47BABHV7M0VQYSYDRGNV', 'edited-photo-20.jpg', 'public', 'cms-media/edited-photo-20.jpg', 'image/jpeg', 2483771, '33b4cf4061fdbbabbe0d0e137461b6595451315ff132dbee7537fa08fcb9f190', true, false, '{}'::jsonb, NOW(), NOW(), NOW(), 'system'),
  ('file_asset_01KYSW47BADXRQ31KE2K67FMG0', 'static_page_attachment', 'cms_media_01KYSW47BA1WDEAGRM5QK8CNQT', 'edited-photo-21.jpg', 'public', 'cms-media/edited-photo-21.jpg', 'image/jpeg', 945671, 'e0ae9611c4f22b327f113971788cece250931e88bf4189d29c9464c43f44159d', true, false, '{}'::jsonb, NOW(), NOW(), NOW(), 'system'),
  ('file_asset_01KYSW47BABDC7DXV4TT2SSYZ4', 'static_page_attachment', 'cms_media_01KYSW47BANY3367FSXBPP5YW2', 'edited-photo-22.jpg', 'public', 'cms-media/edited-photo-22.jpg', 'image/jpeg', 975825, 'da12471bd8a331f905aeea21143412c41afe8efb854fb5a0e29c8138af5a3726', true, false, '{}'::jsonb, NOW(), NOW(), NOW(), 'system'),
  ('file_asset_01KYSW47BA6ZHC1J9Z10X334DF', 'static_page_attachment', 'cms_media_01KYSW47BAHC88170MAR8GW1FY', 'edited-photo-23.jpg', 'public', 'cms-media/edited-photo-23.jpg', 'image/jpeg', 683077, 'c25c7f915ac197dd42c9e1ac8f02adf944396554208736f310a697b4908ff6d3', true, false, '{}'::jsonb, NOW(), NOW(), NOW(), 'system'),
  ('file_asset_01KYSW47BAFDW9QVXA4V8H14HG', 'static_page_attachment', 'cms_media_01KYSW47BA5E3032XRVX9HKFQZ', 'edited-photo-24.jpg', 'public', 'cms-media/edited-photo-24.jpg', 'image/jpeg', 889525, '2bf7414de7f6cbafde7989f6e1d214722113253bae9d78495795d1d57203a29d', true, false, '{}'::jsonb, NOW(), NOW(), NOW(), 'system'),
  ('file_asset_01KYSW47BAD5NXSP3C8JPBNAME', 'static_page_attachment', 'cms_media_01KYSW47BA2VACDQXGVRPWFYCK', 'edited-photo-25.jpg', 'public', 'cms-media/edited-photo-25.jpg', 'image/jpeg', 599873, 'bfb8cb5f9a30d10abacae72ae1d6f891aa48e187d3bc3c17b2792358ec1a3794', true, false, '{}'::jsonb, NOW(), NOW(), NOW(), 'system'),
  ('file_asset_01KYSW47BA7ZX6AF40X8Y88R7D', 'static_page_attachment', 'cms_media_01KYSW47BA23GVVHBD3HFDN5N2', 'edited-photo-26.jpg', 'public', 'cms-media/edited-photo-26.jpg', 'image/jpeg', 687364, '98fc76d76855ef451658ed8c9bbb5f8b53e46c298a98f6e011253bc31985f5c5', true, false, '{}'::jsonb, NOW(), NOW(), NOW(), 'system'),
  ('file_asset_01KYSW47BA027GFAPRVVVXY824', 'static_page_attachment', 'cms_media_01KYSW47BAX25ACC225PX9RYMX', 'edited-photo-27.jpg', 'public', 'cms-media/edited-photo-27.jpg', 'image/jpeg', 1083166, 'e718c1400ffe021d91e0ba421ba75bcb3dd179724d55c40081e7a3131765cced', true, false, '{}'::jsonb, NOW(), NOW(), NOW(), 'system'),
  ('file_asset_01KYSW47BAHY5T755XZJYAC2HG', 'static_page_attachment', 'cms_media_01KYSW47BAHHC2W82Y65DZ6R9D', 'edited-photo-28.jpg', 'public', 'cms-media/edited-photo-28.jpg', 'image/jpeg', 990502, '32e4810656eab4f1265f3f1c160d9c9edc198210224fe2320c956c91e31e1a2d', true, false, '{}'::jsonb, NOW(), NOW(), NOW(), 'system'),
  ('file_asset_01KYSW47BAT26N34X27X8HM2V8', 'static_page_attachment', 'cms_media_01KYSW47BA7FWEXW4ECWYJ34Z1', 'edited-photo-03.jpg', 'public', 'cms-media/edited-photo-03.jpg', 'image/jpeg', 1538855, 'faf2edd3d7e3c55bb8fd3fc7a1655e50e4e8d92df2376941a2c1b28211a7c4ff', true, false, '{}'::jsonb, NOW(), NOW(), NOW(), 'system'),
  ('file_asset_01KYSW47BAV54GN0NT0EH1RZ4F', 'static_page_attachment', 'cms_media_01KYSW47BAQQATX64R5C0GXB5Q', 'edited-photo-04.jpg', 'public', 'cms-media/edited-photo-04.jpg', 'image/jpeg', 1683545, '587bd081415a3fd892a147b63c922d02d540043f1698b41be0d195f8462510b7', true, false, '{}'::jsonb, NOW(), NOW(), NOW(), 'system'),
  ('file_asset_01KYSW47BAYZEBBT17RVKQR2B4', 'static_page_attachment', 'cms_media_01KYSW47BAC8A2188B754F25C0', 'edited-photo-05.jpg', 'public', 'cms-media/edited-photo-05.jpg', 'image/jpeg', 1640343, '021f72381da59f0dff544c4204f792b93c8fae7f5d251c5011ad81b716014338', true, false, '{}'::jsonb, NOW(), NOW(), NOW(), 'system'),
  ('file_asset_01KYSW47BAQPPADXJFTMFSXSY6', 'static_page_attachment', 'cms_media_01KYSW47BAPP01JY2ASEGD2T0D', 'edited-photo-06.jpg', 'public', 'cms-media/edited-photo-06.jpg', 'image/jpeg', 1656731, 'dfd86754ce4ae1445524dbdf6d6901bfdb75b8703d960fbee8cf258e1611d169', true, false, '{}'::jsonb, NOW(), NOW(), NOW(), 'system'),
  ('file_asset_01KYSW47BAFX14P8YD465FY4ZR', 'static_page_attachment', 'cms_media_01KYSW47BA8R7GT6EF31KARNNK', 'edited-photo-07.jpg', 'public', 'cms-media/edited-photo-07.jpg', 'image/jpeg', 2347799, '83140a31b5bfe0e374865f543e51e7ae461028c9a3be2245eb6fc047cfd9b587', true, false, '{}'::jsonb, NOW(), NOW(), NOW(), 'system'),
  ('file_asset_01KYSW47BAFWGHVNEB0KVC459D', 'static_page_attachment', 'cms_media_01KYSW47BAG5MFBE507ZFGV2QF', 'edited-photo-08.jpg', 'public', 'cms-media/edited-photo-08.jpg', 'image/jpeg', 2415159, '1eea5dc41be38738ac2e75f5fb91fa7ee7b381281a545acb9449be970af7cb49', true, false, '{}'::jsonb, NOW(), NOW(), NOW(), 'system'),
  ('file_asset_01KYSW47BAZ50Q2X1TGTJFERW9', 'static_page_attachment', 'cms_media_01KYSW47BA8DRN5X5H1W9BBBGW', 'edited-photo-09.jpg', 'public', 'cms-media/edited-photo-09.jpg', 'image/jpeg', 997500, '34a942743cdf128b1faa6a149b68c5b2d123ee812aef7c9d226f153aaf019c06', true, false, '{}'::jsonb, NOW(), NOW(), NOW(), 'system'),
  ('file_asset_01KYSW47BAY33A9WVZ0QR53ZQ2', 'static_page_attachment', 'cms_media_01KYSW47BA273NBPC0Y974RNPT', 'edited-photo-copy.jpg', 'public', 'cms-media/edited-photo-copy.jpg', 'image/jpeg', 1707002, '5d9a0e2c067c2596f6b33bdafccf8d9a4090f75a756929945c0fd972b2ef3988', true, false, '{}'::jsonb, NOW(), NOW(), NOW(), 'system'),
  ('file_asset_01KYSW47BABXBSTMAFCW4EK9GD', 'static_page_attachment', 'cms_media_01KYSW47BAA09SSBXYGQT10RD6', 'edited-photo.jpg', 'public', 'cms-media/edited-photo.jpg', 'image/jpeg', 3212908, '221bb8d8b22a20543b10e844722116a0ce71ee48ca9e8a47b2b541c23a8c245e', true, false, '{}'::jsonb, NOW(), NOW(), NOW(), 'system'),
  ('file_asset_01KYSW47BAJYAKCZHKE51BAC96', 'static_page_attachment', 'cms_media_01KYSW47BABXFZHV3C2NW5RW70', 'edited-photo.png', 'public', 'cms-media/edited-photo.png', 'image/png', 3588608, '48c038b5443e7b41d6fb84d480b82a90cec15e5da1ca0cccdc57674de0e8a545', true, false, '{}'::jsonb, NOW(), NOW(), NOW(), 'system'),
  ('file_asset_01KYSW47BAF85DDTXVW8Z05PCR', 'hero_banner', 'cms_media_01KYSW47BAPJHN1AFYSZS29Z3R', 'home-page-header.png', 'public', 'cms-media/home-page-header.png', 'image/png', 6930067, 'c8c15ef1a7f7d2afe5923d1bcf28e749ee3464eb8913978b856a8fb7b583efbf', true, false, '{}'::jsonb, NOW(), NOW(), NOW(), 'system');

-- === STATEMENT 2: 31 cms_media_assets rows ===
INSERT INTO cms_media_assets (id, file_asset_id, media_type, state, alt_text, width, height, published_at, created_at, updated_at, created_by, updated_by) VALUES
  ('cms_media_01KYSW47BA46ZQ4QG8W59SP52H', 'file_asset_01KYSW47BAWB9SCMZ4GV2P8NVB', 'content_block_image', 'draft', NULL, 1581, 2606, NULL, NOW(), NOW(), 'system', 'system'),
  ('cms_media_01KYSW47BA4ZW1GHHCDTAVNC9G', 'file_asset_01KYSW47BAPQ0ZYXH33D2WD0Z5', 'content_block_image', 'draft', NULL, 1482, 2442, NULL, NOW(), NOW(), 'system', 'system'),
  ('cms_media_01KYSW47BA4HSY4DZYWERHQ0TX', 'file_asset_01KYSW47BAC5845PPTB9P8R172', 'content_block_image', 'draft', NULL, 1543, 2274, NULL, NOW(), NOW(), 'system', 'system'),
  ('cms_media_01KYSW47BA7Q3R3AN4E192S1H2', 'file_asset_01KYSW47BAEDAFVNGTDPV9CGCP', 'content_block_image', 'draft', NULL, 1539, 2154, NULL, NOW(), NOW(), 'system', 'system'),
  ('cms_media_01KYSW47BAX7JXZ3333RJZGSVX', 'file_asset_01KYSW47BA62T3CJB1R2YCXW7G', 'content_block_image', 'draft', NULL, 1557, 2650, NULL, NOW(), NOW(), 'system', 'system'),
  ('cms_media_01KYSW47BAWYA7BPSQA91KR5YX', 'file_asset_01KYSW47BAT0PNX5PHGVB1AKFZ', 'content_block_image', 'draft', NULL, 1485, 2331, NULL, NOW(), NOW(), 'system', 'system'),
  ('cms_media_01KYSW47BA1ECS6G74HMCB5CNC', 'file_asset_01KYSW47BA3XPPKBPQ829AKMJE', 'content_block_image', 'draft', NULL, 2728, 4037, NULL, NOW(), NOW(), 'system', 'system'),
  ('cms_media_01KYSW47BA43CZ9M0GRF4JQ8Z7', 'file_asset_01KYSW47BAXA0W9G3J35F7MK59', 'content_block_image', 'draft', NULL, 1706, 2504, NULL, NOW(), NOW(), 'system', 'system'),
  ('cms_media_01KYSW47BATDEX0FBAAPKVWW63', 'file_asset_01KYSW47BA25PXSV18JEWPZXSN', 'content_block_image', 'draft', NULL, 2655, 4149, NULL, NOW(), NOW(), 'system', 'system'),
  ('cms_media_01KYSW47BAAWA7XKR4CJS1A3V1', 'file_asset_01KYSW47BAYJXA4RS6YSBBM85D', 'content_block_image', 'draft', NULL, 2703, 4033, NULL, NOW(), NOW(), 'system', 'system'),
  ('cms_media_01KYSW47BA80FFZGBZD0CMP4ST', 'file_asset_01KYSW47BA28TDPPSYE6P1JSNE', 'content_block_image', 'draft', NULL, 2582, 4025, NULL, NOW(), NOW(), 'system', 'system'),
  ('cms_media_01KYSW47BABHV7M0VQYSYDRGNV', 'file_asset_01KYSW47BABC5SMGFHB43Q19D1', 'content_block_image', 'published', 'Trustees honored with garlands and awards at a foundation ceremony', 3160, 4855, NOW(), NOW(), NOW(), 'system', 'system'),
  ('cms_media_01KYSW47BA1WDEAGRM5QK8CNQT', 'file_asset_01KYSW47BADXRQ31KE2K67FMG0', 'content_block_image', 'draft', NULL, 1560, 2253, NULL, NOW(), NOW(), 'system', 'system'),
  ('cms_media_01KYSW47BANY3367FSXBPP5YW2', 'file_asset_01KYSW47BABDC7DXV4TT2SSYZ4', 'content_block_image', 'draft', NULL, 1681, 2595, NULL, NOW(), NOW(), 'system', 'system'),
  ('cms_media_01KYSW47BAHC88170MAR8GW1FY', 'file_asset_01KYSW47BA6ZHC1J9Z10X334DF', 'content_block_image', 'draft', NULL, 1302, 1961, NULL, NOW(), NOW(), 'system', 'system'),
  ('cms_media_01KYSW47BA5E3032XRVX9HKFQZ', 'file_asset_01KYSW47BAFDW9QVXA4V8H14HG', 'content_block_image', 'draft', NULL, 1411, 2100, NULL, NOW(), NOW(), 'system', 'system'),
  ('cms_media_01KYSW47BA2VACDQXGVRPWFYCK', 'file_asset_01KYSW47BAD5NXSP3C8JPBNAME', 'content_block_image', 'published', 'Community gathering — devotees seated together at the temple', 1140, 1889, NOW(), NOW(), NOW(), 'system', 'system'),
  ('cms_media_01KYSW47BA23GVVHBD3HFDN5N2', 'file_asset_01KYSW47BA7ZX6AF40X8Y88R7D', 'content_block_image', 'published', 'Temple community event — seated gathering', 1366, 1929, NOW(), NOW(), NOW(), 'system', 'system'),
  ('cms_media_01KYSW47BAX25ACC225PX9RYMX', 'file_asset_01KYSW47BA027GFAPRVVVXY824', 'content_block_image', 'published', 'Temple community gathering with seated attendees', 1635, 2401, NOW(), NOW(), NOW(), 'system', 'system'),
  ('cms_media_01KYSW47BAHHC2W82Y65DZ6R9D', 'file_asset_01KYSW47BAHY5T755XZJYAC2HG', 'content_block_image', 'draft', NULL, 1481, 2407, NULL, NOW(), NOW(), 'system', 'system'),
  ('cms_media_01KYSW47BA7FWEXW4ECWYJ34Z1', 'file_asset_01KYSW47BAT26N34X27X8HM2V8', 'content_block_image', 'published', 'Community of trustees standing together in the temple hall', 2493, 4110, NOW(), NOW(), NOW(), 'system', 'system'),
  ('cms_media_01KYSW47BAQQATX64R5C0GXB5Q', 'file_asset_01KYSW47BAV54GN0NT0EH1RZ4F', 'content_block_image', 'published', 'Ceremony with decorated shrine and sacred lamp', 2724, 4055, NOW(), NOW(), NOW(), 'system', 'system'),
  ('cms_media_01KYSW47BAC8A2188B754F25C0', 'file_asset_01KYSW47BAYZEBBT17RVKQR2B4', 'content_block_image', 'published', 'Trustees gathered around the temple shrine with floral offerings', 2704, 4117, NOW(), NOW(), NOW(), 'system', 'system'),
  ('cms_media_01KYSW47BAPP01JY2ASEGD2T0D', 'file_asset_01KYSW47BAQPPADXJFTMFSXSY6', 'content_block_image', 'draft', NULL, 2648, 3844, NULL, NOW(), NOW(), 'system', 'system'),
  ('cms_media_01KYSW47BA8R7GT6EF31KARNNK', 'file_asset_01KYSW47BAFX14P8YD465FY4ZR', 'content_block_image', 'draft', NULL, 3007, 4774, NULL, NOW(), NOW(), 'system', 'system'),
  ('cms_media_01KYSW47BAG5MFBE507ZFGV2QF', 'file_asset_01KYSW47BAFWGHVNEB0KVC459D', 'content_block_image', 'draft', NULL, 3116, 4755, NULL, NOW(), NOW(), 'system', 'system'),
  ('cms_media_01KYSW47BA8DRN5X5H1W9BBBGW', 'file_asset_01KYSW47BAZ50Q2X1TGTJFERW9', 'content_block_image', 'draft', NULL, 1502, 2379, NULL, NOW(), NOW(), 'system', 'system'),
  ('cms_media_01KYSW47BA273NBPC0Y974RNPT', 'file_asset_01KYSW47BAY33A9WVZ0QR53ZQ2', 'content_block_image', 'draft', NULL, 2702, 4406, NULL, NOW(), NOW(), 'system', 'system'),
  ('cms_media_01KYSW47BAA09SSBXYGQT10RD6', 'file_asset_01KYSW47BABXBSTMAFCW4EK9GD', 'content_block_image', 'draft', NULL, 3404, 5194, NULL, NOW(), NOW(), 'system', 'system'),
  ('cms_media_01KYSW47BABXFZHV3C2NW5RW70', 'file_asset_01KYSW47BAJYAKCZHKE51BAC96', 'content_block_image', 'draft', NULL, 1281, 2158, NULL, NOW(), NOW(), 'system', 'system'),
  ('cms_media_01KYSW47BAPJHN1AFYSZS29Z3R', 'file_asset_01KYSW47BAF85DDTXVW8Z05PCR', 'hero_desktop', 'published', 'Temple interior — carved wooden pillars and natural light streaming through the doorway', 2786, 2094, NOW(), NOW(), NOW(), 'system', 'system');

-- === STATEMENT 3: 1 hero_banners row ===
INSERT INTO hero_banners (id, title, subtitle, cta_label, cta_url, image_file_id, mobile_image_file_id, state, display_order, starts_at, created_at, updated_at, created_by, updated_by) VALUES
  ('hero_01KYSW47BABQEFBTYQ5WPE8Z33', 'Preserving Sacred Traditions', 'Daily pooja, Annadanam, and the care of our temple — sustained by your seva.', 'See Our Campaigns', '/campaigns', 'cms_media_01KYSW47BAPJHN1AFYSZS29Z3R', NULL, 'published', 1, NOW(), NOW(), NOW(), 'system', 'system');

-- === STATEMENT 4: 1 hero_banner_pages row ===
INSERT INTO hero_banner_pages (hero_banner_id, static_page_id, display_order, created_at) VALUES
  ('hero_01KYSW47BABQEFBTYQ5WPE8Z33', 'static_page_0001N6BR4YWB4RECDQ8H03DTYR', 0, NOW());

-- === STATEMENT 5: UPDATE home JSONB ===
UPDATE static_pages SET
  homepage_content = jsonb_set(
    jsonb_set(
      jsonb_set(
        jsonb_set(
          homepage_content,
          '{story,image_file_id}', '"cms_media_01KYSW47BA7FWEXW4ECWYJ34Z1"'::jsonb
        ),
        '{programs,0,image_file_id}', '"cms_media_01KYSW47BAQQATX64R5C0GXB5Q"'::jsonb
      ),
      '{programs,1,image_file_id}', '"cms_media_01KYSW47BA2VACDQXGVRPWFYCK"'::jsonb
    ),
    '{programs,2,image_file_id}', '"cms_media_01KYSW47BAC8A2188B754F25C0"'::jsonb
  ),
  updated_at = NOW(),
  updated_by = 'system'
WHERE slug = 'home';

-- === STATEMENT 6: UPDATE about JSONB ===
UPDATE static_pages SET
  about_page_content = jsonb_set(
    jsonb_set(
      jsonb_set(
        jsonb_set(
          about_page_content,
          '{values,image_file_id}', '"cms_media_01KYSW47BABHV7M0VQYSYDRGNV"'::jsonb
        ),
        '{trustees,0,photo_file_id}', '"cms_media_01KYSW47BA7FWEXW4ECWYJ34Z1"'::jsonb
      ),
      '{trustees,1,photo_file_id}', '"cms_media_01KYSW47BAX25ACC225PX9RYMX"'::jsonb
    ),
    '{trustees,2,photo_file_id}', '"cms_media_01KYSW47BA23GVVHBD3HFDN5N2"'::jsonb
  ),
  updated_at = NOW(),
  updated_by = 'system'
WHERE slug = 'about';
